### PR TITLE
Link release checklist to repo list (fix #4)

### LINKED ISSUE #4: Add "help wanted" label to next Release Checklist issue template
Related to the next round of releases after #26: If [issues.R](https://github.com/fmichonneau/carpenter/blob/2eb7f9f9d869bb34a626c749207a6b87e55cc63d/R/issues.R) included this GitHub default label, the release checklist would [get hyperlinked on the Software/Data/Library Carpentrie' repo list](https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels).

I'm not entirely sure whether labels are implicitely supported by [`gh`](https://github.com/r-lib/gh/blob/master/R/package.R#L119-L122), since a the `...` parameter is present, I guess they can be inserted and processed.

### PR DESCRIPTION
**Pull request by katrinleinweber**
A naive attempt to implement #4 after based on https://developer.github.com/v3/issues/#create-an-issue.

### CODE REVIEW

**Comment by fmichonneau** [comment]
that's a good idea! Would you mind making `labels` an argument of the function with "help wanted" as default rather than hard coding it in the body?

**Comment by katrinleinweber** [comment]
Like this? I like a hardcoding, though, because that could be combined with other labels using something like `labels <- append(labels, "help wanted")`. Right now, the default could be overwritten.

**Comment by fmichonneau** [comment]
Thanks for this! I like to keep the flexibility of being to override if the issues to be open are not suitable to have the "help wanted" label.

**Comment by katrinleinweber** [comment]
Got it, thanks! I was seeing this from _only_ the release issues perspective.

**Pull request merged**
